<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<!-- 
	Frank Zhao, May 2013
	Syntax highlighting for the rPeANUt assembler
	Install into Preferences -> Browse Packages... -> User\
-->
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>rpeanut</string>
		<string>rpe</string>
		<string>rp</string>
		<string>rps</string>
	</array>
	<key>name</key>
	<string>rPeANUt</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>\b(add|sub|mult|div|mod|and|or|xor|neg|not|move|call|return|trap|jump|jumpz|jumpn|jumpnz|reset|push|pop|rotate|load|store|halt)\b</string>
			<key>name</key>
			<string>keyword.source.rpeanut</string>
		</dict>
		<dict>
			<key>match</key>
			<string>;.*$</string>
			<key>name</key>
			<string>comment.source.rpeanut</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^.+[ 	]*:</string>
			<key>name</key>
			<string>constant.source.rpeanut</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?:^|\s+)(#\w+)</string>
			<key>name</key>
			<string>string.source.rpeanut</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.rpeanut</string>
	<key>uuid</key>
	<string>b1ed0cf7-7ed7-46e0-854a-4b3484580b18</string>
</dict>
</plist>
